### ISSUE TITLE
Want any help with this?

### ISSUE THREAD

**Issue by JamieShelley** [AMLResearchProject/AML-Drug-Discovery#1]

**Comment by javeharron** [comment]
Sure. You got any experience with computational chemistry?

**Comment by AdamMiltonBarker** [comment]
Hi mate. I can add you to the group and introduce you mate, John I know Jamie mate.

**Comment by javeharron** [comment]
I thought I was already added?

**Comment by AdamMiltonBarker** [comment]
I was meaning I will add Jamie to the group. Normal way of people getting involved in the project is through pull requests, I will upload a guide on this but the general guide can be found at the bottom of this tutorial:

https://github.com/AMLResearchProject/AML-Detection-System/tree/master/Security/Server

I will add the projects and get the base structure uploaded to this repo today and update the research blog.
