### ISSUE TITLE
Found a dataset and model example from github:

### ISSUE THREAD

**Issue by JamieShelley** [AMLResearchProject/AML-Drug-Discovery#10]
I suggest we ask for permission
 (Email: 1210307427@pku.edu.cn or kevinid4g@gmail.com) 
and use it as a base in our system considering the time restraints.
Paper: https://arxiv.org/abs/1801.07299

I suggest our addition is an additional bias link from the discriminator.

Github link:
https://github.com/kevinid/molecule_generator

**Comment by AdamMiltonBarker** [comment]
Hi Jamie thanks for posting an issue. We have added a template for feature requests and bugs. Please could you create a new feature request following the guide in the template and providing the specified information.

Once the team receives the feature request it will be reviewed by the team and action taken depending on the outcome. 

https://github.com/AMLResearchProject/AML-Drug-Discovery/issues/new?assignees=&labels=&template=feature_request.md&title=
