### ISSUE TITLE
Providing links for general research into molecule standards

### ISSUE THREAD

**Issue by javeharron** [AMLResearchProject/AML-Drug-Discovery#7]
https://www.drugbank.ca/documentation

https://arxiv.org/pdf/1805.11973.pdf

http://www.samedanltd.com/…/9908ae04a14145d662675ac2eb0e0e5…

Process overview:
https://www.fda.gov/…/developmentapprovalprocess/default.htm

https://docs.chemaxon.com/display/docs/Molecule+Formats

https://www.click2drug.org/directory_PrepareSmallMolecules.…

https://www.ncbi.nlm.nih.gov/…/…/PMC1978274/pdf/0707305a.pdf

https://en.wikipedia.org/wiki/Chemical_file_format…

https://www.nature.com/articles/ncomms10331

https://insilicotrials.com/platform/

https://github.com/kumar1202/Drug-Discovery-using-GANs

https://github.com/mostafachatillon/ChemGAN-challenge

**Comment by AdamMiltonBarker** [comment]
Hi @javeharron we have added a template for feature requests. Please could you create a new issue following the guide in the template and providing the specified information. 

We will generally not post lists of links into feature requests, please feel free to submit a pull request to the project's research repository with a new file containing your directory and descriptions of why they are relevant to the project, you could link back to your issue where you can continue to plan with the community. We generally will not approve documentation and code that does not maintain the style and format of the rest of the repository so please bear this in mind.

https://github.com/AMLResearchProject/AML-Project-Research

Thank you contributing today.
