### ISSUE TITLE
test push/pull request to master

### ISSUE THREAD

**Issue by javeharron** [AMLResearchProject/AML-Drug-Discovery#9]
test push/pull on local vs master repo

**Comment by AdamMiltonBarker** [comment]
Hi John sorry test pushes will not be merged into repositories. You did complete the request correctly though :)

**Comment by AdamMiltonBarker** [comment]
Hi John we don't push tests into the repo. In addition I found no pull request.

**Comment by AdamMiltonBarker** [comment]
Hi @javeharron  how are you? 

We generally will not expect to have test issues or test pull requests submitted to the repository. We have now created issue and pull requests templates so this should give you a good guideline on how to submit a feature request or bug. 

Thanks again.
